#!/bin/bash

config_file="$HOME/.config/bwall/bwall.conf"

initialize() {
	mkdir -p "$HOME/.config/bwall"
	touch "$config_file"

	# Assign monitor resolution
	monitor_resolution=$(xrandr | awk '/*/ {print $1}')
	echo "monitor_resolution='$monitor_resolution'" >> $config_file

	# Extract width and height from resolution
	IFS='x' read -r monitor_width monitor_height <<< "$monitor_resolution"
	echo "monitor_width='$monitor_width'" >> $config_file
	echo "monitor_height='$monitor_height'" >> $config_file
}

run_loop() {
	source $config_file
	echo $monitor_resolution
	echo $monitor_width
	echo $monitor_height
}

if [ -f "$HOME/.config/bwall/bwall.conf" ]; then
	run_loop
else
	initialize
fi
